FROM nginx:latest
RUN apt-get update && apt-get install -y openssl
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY ssl /etc/nginx/ssl
RUN mkdir -p /var/cache/nginx && chown -R nginx:nginx /var/cache/nginx
CMD ["nginx", "-g", "daemon off;"]
